server {
    listen 80;

    # 1. ТУТ ЖИВЕТ РЕАКТ
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. ТУТ ЖИВЕТ БЭКЕНД
    # Теперь бэкенд доступен ТОЛЬКО по адресу /api/
    location /api/ {
        proxy_pass http://api:8000/; # слеш в конце важен!
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
